import os
import json
import datetime
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request

# Define the scopes
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
CLIENT_SECRETS_FILE = "client_secrets.json"
TOKEN_FILE = "token.json"

def get_authenticated_service():
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(CLIENT_SECRETS_FILE):
                raise FileNotFoundError(f"{CLIENT_SECRETS_FILE} not found. Please download it from Google Cloud Console.")
            
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRETS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        
        # Save the credentials for the next run
        with open(TOKEN_FILE, "w") as token:
            token.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)

def upload_video():
    # Load topic data
    input_path = os.path.join('.tmp', 'topic_data.json')
    video_path = os.path.join('.tmp', 'final_video.mp4')
    
    if not os.path.exists(input_path):
        print("topic_data.json not found.")
        return
    if not os.path.exists(video_path):
        print("final_video.mp4 not found.")
        return

    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    youtube = get_authenticated_service()

    title = data.get('topic', 'Daily Shorts Video').strip()
    if len(title) > 100:
        title = title[:97] + "..."
    
    description = data.get('description', 'Generated by AI Agent')
    keywords = data.get('keywords', [])

    print(f"Uploading video: {title}")
    
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": keywords,
            "categoryId": "22" # People & Blogs
        },
        "status": {
            "privacyStatus": "private", # Default to private for safety
            "selfDeclaredMadeForKids": False
        }
    }

    media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
    
    request = youtube.videos().insert(
        part=",".join(body.keys()),
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Uploaded {int(status.progress() * 100)}%")

    print(f"Upload Complete! Video ID: {response['id']}")

if __name__ == "__main__":
    upload_video()
